apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command:
      - sleep
      - "infinity"
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.100.0.10
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
      - ap-northeast-2.compute.internal
    options:
      - name: ndots
        value: "1"