apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-websrv
  template:
    metadata:
      labels:
        app: deploy-websrv
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: aews-websrv
        image: k8s.gcr.io/echoserver:1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-deploy-echo
  namespace: default
spec:
  type: NodePort
  selector:
    app: deploy-websrv
  ports:
    - name: http
      port: 8080          # 클러스터 내부 서비스 포트
      targetPort: 8080    # Pod의 컨테이너 포트 (Deployment와 동일)
      nodePort: 30082     # 노드 외부에서 접근할 포트