apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-snapshot-restored-claim
spec:
  storageClassName: gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  dataSource:
    name: ebs-claim-every-5min-202510200520 # check myself 
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
